name: Publish to Nuget
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build
      run: dotnet build -c Release -p:Version=${{ github.event.release.tag_name }}
      working-directory: ./ModelToRdf/

    - name: Test
      run: dotnet test

    - name: Create NuGet Package
      run: dotnet pack -c Release -p:PackageVersion=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/gabrieldelaparra/ModelToRdf/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ./ModelToRdf/
    
    - name: Archive NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: ModelToRdf
        path: ./ModelToRdf/bin/Release/ModelToRdf.${{ github.event.release.tag_name }}.nupkg
    
    - name: Publish Nuget Package
      run: dotnet nuget push ./ModelToRdf/bin/Release/ModelToRdf.${{ github.event.release.tag_name }}.nupkg --api-key ${{ SECRETS.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      run: dotnet nuget push ./ModelToRdf/bin/Release/ModelToRdf.${{ github.event.release.tag_name }}.nupkg --source https://nuget.pkg.github.com/gabrieldelaparra/ModelToRdf/index.json
